spring.application.name=Module05-Spring-AI-Multi-Model-Support

server.port=6794

############ Ollama ###########
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3.2:3b

############ OpenAI ###########
#spring.ai.openai.api-key=YOUR_KEY
#spring.ai.openai.chat.options.model=gpt-4o-mini

#Gemini API
gemini.api.base-url=https://generativelanguage.googleapis.com/v1beta/models
gemini.api.model=gemini-3-flash-preview
gemini.api.key=${GEMINI_API_KEY}
